FROM ubuntu:14.04 
MAINTAINER Matthew Boeh <m@mboeh.com>

# Essential packages that every container will need
RUN apt-get update && apt-get -y install \
  locales \
  wget \
  libpq-dev \
  git \
  build-essential \
  ruby
